Sidebar
gregorywhytepatriots/techDraft pull request #35
Opened 2019-05-17 14:22 UTC by rizgararab

2019-05-17 14:33 UTC, jp-2019 requested changes
move code from css file to html code. 
extra spacing must be removed. 
code isn't running.

2019-05-17 15:37 UTC, jp-2019 commented on angular-techDraft/src/app/top-nav-bar/top-nav-bar.component.html
> +
remove extra spacing

2019-05-17 15:37 UTC, jp-2019 reviewed
need menu button image (need to add image asset)

2019-05-17 15:40 UTC, jp-2019 approved these changes

2019-05-17 15:42 UTC, JaredHook requested changes
pull request is looking to delete integral files

2019-05-17 15:53 UTC, jp-2019 submitted a review, later dismissed
what's going on with the delete files??

2019-05-18 23:12 UTC, shakirullah7892 commented
I agree with Jared and Jeaniie

2019-05-21 14:49 UTC, rizgararab commented on angular-techDraft/src/app/top-nav-bar/top-nav-bar.component.html
> +
extra spacing removed

2019-05-21 14:58 UTC, rizgararab reviewed
changes has been done

2019-05-21 15:02 UTC, jp-2019 commented on angular-techDraft/src/app/app.module.ts
> -
-?

2019-05-22 13:08 UTC, shakirullah7892 commented on angular-techDraft/src/app/ggithab-button/ggithab-button.component.html
> +
extra spacing has to be removed.

2019-05-22 13:08 UTC, shakirullah7892 commented on angular-techDraft/src/app/ggithab-button/ggithab-button.component.html
> +
extra spacing has to be removed here too.

2019-05-22 13:09 UTC, shakirullah7892 commented on angular-techDraft/src/app/newsletterform/newsletterform.component.css
> +
extra line needs to removed.

2019-05-22 13:10 UTC, shakirullah7892 commented on angular-techDraft/src/app/newsletterform/newsletterform.component.html
> +
extra line needs to be removed here too.

2019-05-22 13:12 UTC, shakirullah7892 commented on angular-techDraft/src/app/sidebar/sidebar.component.spec.ts
> +      declarations: [ SidebarComponent ]
All of the sidebar spect.ts has to be reverted.

2019-05-22 14:08 UTC, rizgararab commented
All approved by Shak

2019-05-22 14:08 UTC, rizgararab commented
Approved

2019-05-22 14:25 UTC, JaredHook approved these changes

2019-05-22 14:29 UTC, JaredHook approved these changes

2019-05-22 14:31 UTC, JaredHook approved these changes

2019-05-22 14:33 UTC, shakirullah7892 approved these changes

2019-05-22 14:33 UTC, merged